repos:
  # Language agnostic hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict

  # Format code
  # https://github.com/nicklockwood/SwiftFormat
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.55.5
    hooks:
      - id: swiftformat
        entry: swiftformat

  # Lint code
  # https://realm.github.io/SwiftLint/
  - repo: https://github.com/realm/SwiftLint
    rev: 0.58.2
    hooks:
      - id: swiftlint
        entry: swiftlint --fix --strict

  # Ensure conventional commit
  # https://commitizen-tools.github.io/commitizen/tutorials/auto_check/
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.1
    hooks:
      - id: commitizen

